# Generated by Django 3.1.3 on 2020-11-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_order_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productName',
        ),
    ]
