# Generated by Django 3.1.3 on 2020-11-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0004_auto_20201130_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productName',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
    ]
