# Generated by Django 3.1.3 on 2020-11-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0005_auto_20201130_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dateCreated',
            new_name='date_ordered',
        ),
    ]
