# Generated by Django 3.1.3 on 2020-12-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0008_auto_20201203_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(default='default_pic', upload_to=''),
        ),
    ]
